CREATE TABLE incidents (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           workspace_id BIGINT NOT NULL,
                           title VARCHAR(500) NOT NULL,
                           description TEXT,
                           severity VARCHAR(20) NOT NULL,
                           status VARCHAR(20) NOT NULL,
                           assigned_to VARCHAR(255),
                           mention_count INT DEFAULT 0,
                           resolution_percent INT DEFAULT 0,
                           requires_immediate_action BOOLEAN DEFAULT FALSE,
                           pattern_keyword VARCHAR(255),
                           detected_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                           resolved_at TIMESTAMP(6) WITH TIME ZONE,
                           created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                           updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                           PRIMARY KEY (id)
);

CREATE INDEX idx_incidents_workspace_status ON incidents (workspace_id, status);
CREATE INDEX idx_incidents_workspace_action ON incidents (workspace_id, requires_immediate_action);