# Server
spring.application.name=brandradar-backend
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/BrandRadar_DB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=brandradar.shared.infrastructure.persistence.jpa.strategy.SnakeCasePhysicalNamingStrategy
# Flyway
spring.flyway.enabled=false

# GROQ AI
groq.api.key=${GROQ_API_KEY:default-groq-key}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.3-70b-versatile

# JWT
jwt.secret=${JWT_SECRET:brandradar-super-secret-key-change-in-production-min32chars}
jwt.expiration=${JWT_EXPIRATION_MS:900000}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

springdoc.packages-to-scan=brandradar
springdoc.paths-to-match=/api/**

# Abrir navegador automáticamente
spring.devtools.restart.enabled=true
