# Server
spring.application.name=brandradar-backend
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/BrandRadar_DB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.flyway.enabled=false

# GROQ AI
groq.api.key=${GROQ_API_KEY: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}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.3-70b-versatile

# YouTube API
youtube.api.key=${YOUTUBE_API_KEY:AIzaSyCy2AVo-QLiAISm-Ta1S9GeHcONvVs4M_8}
youtube.api.url=https://www.googleapis.com/youtube/v3

# JWT
jwt.secret=${JWT_SECRET:brandradar-secret-key-2026-very-long-and-secure}
jwt.expiration.ms=86400000
jwt.refresh.expiration.ms=604800000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

springdoc.packages-to-scan=brandradar
springdoc.paths-to-match=/api/**

# Abrir navegador automáticamente
spring.devtools.restart.enabled=true